   services:
     backend:
       build:
         context: ./backend
       ports:
         - "3000:3000"
       environment:
         - PORT=3000
       volumes:
         - ./backend:/usr/src/app
       restart: always

     frontend:
       build:
         context: ./frontend
       ports:
         - "80:80"
       restart: always