services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:3000"  # Use an environment variable for the external port
    environment:
      - PORT=3000  # Internal container port, matching the app’s `EXPOSE`
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  # Placeholder for frontend service
  # Uncomment and configure this when the frontend is ready
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - PORT=3000
  #   volumes:
  #     - ./frontend:/app
